version: '3'
services:
  client:
    image: wafahmi/multi-client
    mem_limit: 128m
    hostname: client
  api:
    image: wafahmi/multi-api
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: wafahmi/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: wafahmi/multi-nginx
    mem_limit: 128m
    hostname: worker
    ports:
      - 80:80